Update to upstream (1.0.4) version

diff --git a/pacadd b/pacadd
--- a/pacadd
+++ b/pacadd
@@ -33,35 +33,35 @@ if [[ "$repo_url" != *:*/* ]]; then echo "error: invalid address"; exit 3; fi
 case "$1" in
 -h|--help|help)
 cat <<__EOF__
-pacadd v1.0.3
+pacadd v1.0.4
 
 A simple tool for managing repositories
 
 Usage: pacadd [options] NAME URL [options]
 
-  -a, --add NAME URL			Adds [NAME] and Server=URL to $conf_f
-  	-a URL -i			Adds Server=URL to $conf_i or <path> (if declared)
+  -a, --add 'NAME' 'URL'		Adds [NAME] and Server=URL to $conf_f
+  	-a 'URL' -i			Adds Server=URL to $conf_i or <path> (if declared)
   	-a NAME -i			Adds [NAME] and Include=$conf_i or <path> (if declared) to $conf_f
-  	-a NAME -s URL -i		Adds [NAME] and Include=$conf_i to $conf_f; Server=URL to $conf_i
-  	-a NAME -s URL -i <path>	Adds [NAME] and Include=<path> to $conf_f;  Server=URL to <path>
-	-a NAME -ts URL			Adds [NAME] and Server=URL/\$repo/os/\$arch to $conf_f
-  	-a URL -ts			Adds Server=URL/\$repo/os/\$arch to $conf_i
-  	-a URL -ts -i			Adds Server=URL/\$repo/os/\$arch to $conf_i or <path> (if declared)
-  	-a NAME -s URL -i <path> -ts	Adds [NAME] and Include=<path> to $conf_f; Server=URL/\$repo/os/\$arch to $conf_i
-  -r, --remove NAME			Removes [NAME] from $conf_f
-  	-r -m URL			Removes Server=URL from $conf_i
-  	-r -m URL <path>		Removes Server=URL from <path>
-  -c, --comment NAME			Comment out the line of [NAME] from $conf_f
-  -u, --uncomment NAME			Uncomment the line of [NAME] from $conf_f
+  	-a NAME -s 'URL' -i		Adds [NAME] and Include=$conf_i to $conf_f; Server=URL to $conf_i
+  	-a NAME -s 'URL' -i <path>	Adds [NAME] and Include=<path> to $conf_f;  Server=URL to <path>
+	-a NAME -ts 'URL'		Adds [NAME] and Server=URL/\$repo/os/\$arch to $conf_f
+  	-a 'URL' -ts			Adds Server=URL/\$repo/os/\$arch to $conf_i
+  	-a 'URL' -ts -i			Adds Server=URL/\$repo/os/\$arch to $conf_i or <path> (if declared)
+  	-a NAME -s 'URL' -i <path> -ts	Adds [NAME] and Include=<path> to $conf_f; Server=URL/\$repo/os/\$arch to $conf_i
+  -r, --remove 'NAME'			Removes [NAME] from $conf_f
+  	-r -m 'URL'			Removes Server=URL from $conf_i
+  	-r -m 'URL' <path>		Removes Server=URL from <path>
+  -c, --comment 'NAME'			Comment out the line of [NAME] from $conf_f
+  -u, --uncomment 'NAME'		Uncomment the line of [NAME] from $conf_f
   -l, --list				Shows all available (uncommented) repositories at $conf_f
-  -c_is_c NAME (or) URL			Checks is [NAME] or Server=URL commented out at $conf_f
-  	-c_is_c URL -i			Checks is Server=URL commented out at $conf_i or <path> (if declared)
+  -c_is_c 'NAME' (or) 'URL'		Checks is [NAME] or Server=URL commented out at $conf_f
+  	-c_is_c 'URL' -i		Checks is Server=URL commented out at $conf_i or <path> (if declared)
   	/ --check_is_commented
-  -c_is_u NAME (or) URL			Checks is [NAME] or Server=URL uncommented at $conf_f
-  	-c_is_c URL -i			Checks is Server=URL commented out at $conf_i or <path> (if declared)
+  -c_is_u 'NAME' (or) 'URL'		Checks is [NAME] or Server=URL uncommented at $conf_f
+  	-c_is_c 'URL' -i		Checks is Server=URL commented out at $conf_i or <path> (if declared)
   	/ --check_is_uncommented
-  -c_is_x NAME (or) URL			Checks is [NAME] or Server=URL exists at $conf_f
-  	-c_is_x URL -i			Checks is Server=URL exist at $conf_i or <path> (if declared)
+  -c_is_x 'NAME' (or) 'URL'		Checks is [NAME] or Server=URL exists at $conf_f
+  	-c_is_x 'URL' -i		Checks is Server=URL exist at $conf_i or <path> (if declared)
   	/ --check_is_exists
 
 __EOF__
@@ -189,7 +189,21 @@ echo "error: unknown argument(s)"; exit 1; fi; fi; fi; fi
 check_root
 if [[ ! "$2" ]]; then
 echo "error: invalid argument(s)"; exit 1; fi
-	if [[ "$2" != "-m" || "$2" != "--mirror" ]]; then
+	if [[ "$2" == "-m" || "$2" == "--mirror" ]]; then
+	if [[ ! "$3" ]]; then
+	echo "error: too few argument(s)"; exit 1; fi
+		if [ "$4" ]; then
+		if ! [ -f "$4" ]; then echo "error: file $4 not exists"; exit 6; fi
+		repo_url="$3"
+		end_file="$4"
+		repo_url="$(echo $repo_url | sed 's:/:\\/:g')"
+		sed "/.*${repo_url}/ d" -i $end_file
+		else
+		repo_url="$3"
+		repo_url="$(echo $repo_url | sed 's:/:\\/:g')"
+		sed "/.*${repo_url}/ d" -i $conf_i
+		fi
+	else
 	repo_name="$2"
 		if ! [[ "$(sed "/.*\[$repo_name\]/! d" $conf_f)" ]]; then
 			echo "error: repository $repo_name not found in $conf_f"; exit 7
@@ -203,19 +217,7 @@ echo "error: invalid argument(s)"; exit 1; fi
 	sed "/^.*\#.*\[$repo_name\]/,/^ *$/d" -i $conf_f; else
 	sed "/^\$*\[$repo_name\]/,/^ *$/d" -i $conf_f
 	fi
-	else
-	if [[ ! "$3" ]]; then
-	echo "error: too few argument(s)"; exit 1; fi
-		if [ "$4" ]; then
-		if ! [ -f "$4" ]; then echo "error: file $4 not exists"; exit 6; fi
-		repo_url="$3"
-		end_file="$4"
-		sed "/.*${repo_url}/ d" -i $end_file
-		else
-		repo_url="$3"
-		sed "/.*${repo_url}/ d" -i $conf_i
-		fi
-	fi
+fi
 ;;
 -u|--uncomment)
 check_root
